name: ftplayer
description: "A video player for FTP server"
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.9.2

dependencies:
    flutter:
        sdk: flutter

    # State management / core
    flutter_riverpod: ^2.5.1
    dio: ^5.9.0
    json_annotation: ^4.9.0

    # Local storage
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    flutter_secure_storage: ^10.0.0

    # Video & playback
    video_player: ^2.9.2
    video_player_pip: ^0.0.8
    wakelock_plus: ^1.2.8

    # Downloads
    flutter_downloader: ^1.11.7

    # Connectivity / device
    connectivity_plus: ^7.0.0
    device_info_plus: ^12.3.0

    # UI and visuals
    google_fonts: ^6.2.1
    flutter_slidable: ^4.0.3
    cached_network_image: ^3.4.1

    # Navigation
    go_router: ^17.0.1

    # Config & logging
    flutter_dotenv: ^6.0.0
    logger: ^2.5.0

    # Forms
    flutter_form_builder: ^10.2.0
    form_builder_validators: ^11.0.0

    # Animation & loading
    animations: ^2.0.11
    flutter_animate: ^4.5.0
    skeletonizer: ^2.1.1
    shimmer_animation: ^2.2.0

    # Refresh
    pull_to_refresh: ^2.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    build_runner: ^2.4.9
    json_serializable: ^6.9.0

flutter:
    uses-material-design: true
    assets:
        - .env
